[package]
name = "backend"
version = "0.1.0"
authors = ["Matti HÃ¤nninen <matti@mjhanninen.com>"]

[dependencies]
lazy_static = "*"
hyper = "*"
iron = "*"
mime = "*"
router = "*"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
